site_name: MyPassword
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - navigation.top
  hide:
    - navigation

nav:
  - Home: index.md
  - Guide: guide.md
  - Security: key-gen.md
  - Backup: backup.md
