site_name: MyPassword
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - navigation.top
  hide:
    - navigation

nav:
  - Home: index.md
  - Guide: guide.md
  - Security: key-gen.md
  - Extension: extension.md
  - Backup: backup.md

copyright: |
  <p>Copyright &copy; 2026 <a href="https://github.com/michaelliao/mypassword">Open Source</a>.</p>
