site_name: MyPassword
theme:
  name: material
  logo: assets/images/logo.svg
  palette:
    primary: teal
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - navigation.top
  hide:
    - navigation

nav:
  - Home: index.md
  - Guide: guide.md
  - Security: key-gen.md
  - Extension: extension.md
  - Backup: backup.md

copyright: |
  <p>MyPassword copyright &copy; 2026. <a href="https://github.com/michaelliao/mypassword/releases/latest">Download</a> | <a href="https://github.com/michaelliao/mypassword">GitHub</a> | <a href="https://mypassword.puppylab.org/privacy/">Privacy</a></p>
