# oauth default client id:

oauth.google.url=
oauth.google.client_id=316516407199-o9kch40i9adm4881k4kl5e9ngrfihoi2.apps.googleusercontent.com

oauth.discord.url=https://discord.com/oauth2/authorize
oauth.discord.client_id=1490177980188856346

