# oauth configuration
# please NOTE the client_secret is required by OAuth PKCE for some providers, but not for security purpose.

oauth.google.auth_url=https://accounts.google.com/o/oauth2/v2/auth
oauth.google.token_url=https://oauth2.googleapis.com/token
oauth.google.client_id=316516407199-o9kch40i9adm4881k4kl5e9ngrfihoi2.apps.googleusercontent.com
oauth.google.client_secret=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

oauth.github.auth_url=https://github.com/login/oauth/authorize
oauth.github.token_url=https://github.com/login/oauth/access_token
oauth.github.client_id=Ov23liFEn9C7XEvQlOeR
oauth.github.client_secret=2fdfa08c8f88da4271a9154e84e8e132f448a5b8

